apiVersion: v1
kind: Service
metadata:
  name: gitops-backend-service
  labels:
    app: gitops-backend
    component: backend
spec:
  type: ClusterIP
  ports:
  - port: 3001
    targetPort: 3001
    protocol: TCP
    name: http
  selector:
    app: gitops-backend
