apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: multi-application-set
  namespace: argocd
spec:
  generators:
  - matrix:
      generators:
      # Application generator - reads from applications-config.yaml
      - list:
          elements:
          - app: voting-app
            displayName: "Voting App (Demo)"
            path: "applications/voting-app"
            enabled: "true"
          - app: todo-app
            displayName: "Todo Management App"
            path: "applications/todo-app/k8s/overlays"
            enabled: "true"
      
      # Environment generator
      - list:
          elements:
          - env: dev
            namespace: "{{app}}-dev"
            syncPolicy: automated
            namePrefix: "dev-"
          - env: staging
            namespace: "{{app}}-staging"
            syncPolicy: automated
            namePrefix: "staging-"
          - env: prod
            namespace: "{{app}}-prod"
            syncPolicy: manual
            namePrefix: "prod-"
  
  template:
    metadata:
      name: '{{app}}-{{env}}'
      labels:
        application: '{{app}}'
        environment: '{{env}}'
        app.kubernetes.io/name: '{{app}}'
        app.kubernetes.io/instance: '{{env}}'
    spec:
      project: gitops-application
      source:
        repoURL: https://github.com/sjlevalley/gitops-application
        targetRevision: HEAD
        path: '{{path}}/{{env}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: '{{syncPolicy}}' == 'automated'
          selfHeal: '{{syncPolicy}}' == 'automated'
        syncOptions:
        - CreateNamespace=true
        - PrunePropagationPolicy=foreground
        - PruneLast=true
      revisionHistoryLimit: 10
