apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-frontend
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: frontend
        env:
        - name: NODE_ENV
          value: "production"
        - name: NEXT_PUBLIC_API_URL
          value: "http://prod-gitops-backend-service:3001"
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "400m"
