# Applications Configuration
# This file defines all available applications that can be deployed via ArgoCD

applications:
  - name: voting-app
    displayName: "Voting App (Demo)"
    description: "Docker Voting App - A complete microservices demo with frontend, backend, and database components"
    path: "applications/voting-app"
    enabled: true
    environments:
      - dev
    imageSource: "Docker Hub"
    components:
      - "Vote Frontend (Python Flask)"
      - "Result Frontend (Node.js)"
      - "Worker (Node.js)"
      - "Redis (In-memory database)"
      - "PostgreSQL (Persistent database)"
    access:
      - "Vote App: http://<master-ip>:30001"
      - "Result App: http://<master-ip>:30002"

  - name: todo-app
    displayName: "Todo Management App"
    description: "Modern todo management application with Next.js frontend, Express backend, and PostgreSQL database"
    path: "applications/todo-app/k8s/overlays"
    enabled: true
    environments:
      - dev
      - staging
      - prod
    imageSource: "Custom Build"
    components:
      - "Frontend (Next.js 15 with React 19)"
      - "Backend (Node.js with Express)"
      - "Database (PostgreSQL 15)"
    access:
      - "Frontend: http://<master-ip>:3000"
      - "Backend API: http://<master-ip>:3001"

  - name: blog-app
    displayName: "Blog Platform"
    description: "A modern blog platform (placeholder for future implementation)"
    path: "applications/blog-app"
    enabled: false
    environments:
      - dev
    imageSource: "TBD"
    components:
      - "Frontend (TBD)"
      - "Backend (TBD)"
      - "Database (TBD)"
    access:
      - "TBD"

  - name: ecommerce-app
    displayName: "E-commerce Store"
    description: "Full-featured e-commerce platform (placeholder for future implementation)"
    path: "applications/ecommerce-app"
    enabled: false
    environments:
      - dev
    imageSource: "TBD"
    components:
      - "Frontend (TBD)"
      - "Backend (TBD)"
      - "Database (TBD)"
      - "Payment Gateway (TBD)"
    access:
      - "TBD"
