apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitops-database-pvc
  labels:
    app: gitops-database
    component: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
