apiVersion: v1
kind: Service
metadata:
  name: gitops-database-service
  labels:
    app: gitops-database
    component: database
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: postgres
  selector:
    app: gitops-database
