apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-backend
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: backend
        env:
        - name: NODE_ENV
          value: "development"
        - name: DB_HOST
          value: "dev-gitops-database-service"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
