apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: gitops-application-dev

namespace: gitops-application-dev

resources:
- ../../base

namePrefix: dev-

commonLabels:
  environment: development

patchesStrategicMerge:
- frontend-patch.yaml
- backend-patch.yaml
- database-patch.yaml

images:
- name: gitops-frontend
  newTag: dev-latest
- name: gitops-backend
  newTag: dev-latest
