apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-database
spec:
  template:
    spec:
      containers:
      - name: postgres
        resources:
          requests:
            memory: "256Mi"
            cpu: "125m"
          limits:
            memory: "512Mi"
            cpu: "250m"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitops-database-pvc
spec:
  resources:
    requests:
      storage: 5Gi
